version: 2.1
jobs:
  buildPackages:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build project
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
          - ./*

  check:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./
      - run: yarn lint
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Set registry URL
          command: npm set registry https://npm.jahia.com/
      - run:
          name: Authenticate with NPM registry
          command: echo '//npm.jahia.com/:_authToken=$NPM_TOKEN' >> .npmrc
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - add_ssh_keys:
          fingerprints:
            - "97:b9:c5:2d:c6:80:4b:fd:e4:2c:73:55:49:cf:a9:34"
      - run: git config --global user.email "jahia-ci@jahia.com"
      - run: git config --global user.name "JahiaCI"
      - run: 
          name: Publish
          command: yarn run publish

workflows:
  version: 2
  build:
    jobs:
      - buildPackages
      - check:
          requires:
            - buildPackages
      - publish:
          requires:
            - check
          filters:
            branches:
              only: master
